// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHqRD9GEb2_V8TYGuwLJ8WYPZ_G26uO0',
    appId: '1:154749565686:web:932c1f0380943337aa4ad7',
    messagingSenderId: '154749565686',
    projectId: 'lecture-map-week2',
    authDomain: 'lecture-map-week2.firebaseapp.com',
    storageBucket: 'lecture-map-week2.appspot.com',
    measurementId: 'G-MQTGMXLCF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeibzam9feLAb3tA0DpS3hdvXv86GDiqw',
    appId: '1:154749565686:android:c32239ad9376ff1caa4ad7',
    messagingSenderId: '154749565686',
    projectId: 'lecture-map-week2',
    storageBucket: 'lecture-map-week2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Z0tgeF3Xrv8I5ZsTpI-iy1gbiTU8jLM',
    appId: '1:154749565686:ios:71390baa5d7f4228aa4ad7',
    messagingSenderId: '154749565686',
    projectId: 'lecture-map-week2',
    storageBucket: 'lecture-map-week2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Z0tgeF3Xrv8I5ZsTpI-iy1gbiTU8jLM',
    appId: '1:154749565686:ios:71390baa5d7f4228aa4ad7',
    messagingSenderId: '154749565686',
    projectId: 'lecture-map-week2',
    storageBucket: 'lecture-map-week2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBHqRD9GEb2_V8TYGuwLJ8WYPZ_G26uO0',
    appId: '1:154749565686:web:2dc7434aee1e1148aa4ad7',
    messagingSenderId: '154749565686',
    projectId: 'lecture-map-week2',
    authDomain: 'lecture-map-week2.firebaseapp.com',
    storageBucket: 'lecture-map-week2.appspot.com',
    measurementId: 'G-K7YNB0HL48',
  );
}
